### PR TITLE
check if ignore_unset_args is set in xmlloader

### PR DESCRIPTION
**Pull request by knorth55**
`ignore_unset_args` is introduced in #1788, but it is set from outside of the class instance.
https://github.com/ros/ros_comm/commit/3fc9b9ba909f9c691897d41401c3eaf47ad6ef02#diff-3157de68f88b12267c21f7208ae4c58c5c9bd4ab1ca2685c2167bc46e96daeb8R445

This PR change to check `ignore_unset_args` attribute is set before calling it.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/knorth55/.cache/dein/.cache/.vimrc/.dein/plugin/rosvim/filetypes/launch.py", line 150, in syntastic_checker
    loader.load(vimp.buf.name, conf, verbose=False)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 763, in load
    if not self.ignore_unset_args:
AttributeError: 'XmlLoader' object has no attribute 'ignore_unset_args'
```

my environment:
ROS: melodic
Ubuntu 18.04
roslaunch: `1.14.12-1bionic.20210921.202835`

### CODE REVIEW

**Comment by yangninghua** [comment]
您好，请问我该怎么修改这些文件？

**Review by sloretz — APPROVED** [review]
Thank you for the PR!
