### ISSUE TITLE
roscpp compilation fails with clang-3.2 and libc++

### ISSUE THREAD

**Issue by severin-lemaignan** [ros/ros_comm#292]
While trying to compile `roscpp` with `clang-3.2` and a fresh checkout of `libc++`, the compilation fails.

The first failure is addressed in #291 
The second failure seems related to headers generated from `gencpp`:

First error:

```
In file included from ros_comm-1.9.47/clients/roscpp/src/libros/service_publication.cpp:42:
/opt/openrobots/include/std_msgs/String.h:68:69: error: implicit instantiation of undefined template 'std::allocator<void>'
typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
^
ros_comm-1.9.47/clients/roscpp/src/libros/service_publication.cpp:139:24: note: in instantiation of template class 'std_msgs::String_<std::allocator<void> >' requested here
std_msgs::String error_string;
^
/opt/openrobots/include/ros/message_forward.h:33:28: note: template is declared here
template<typename T> class allocator;
^
```

Second error:

```
In file included from ros_comm-1.9.47/clients/roscpp/src/libros/service_publication.cpp:42:
/opt/openrobots/include/std_msgs/String.h:68:98: error: 'rebind' following the 'template' keyword does not refer to a template
typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
^~~~~~
```

---

Steps to reproduce (assuming you have `clang` and `libc++` available):
- clone the latest version of `ros_comm`
- `cd ros_comm/clients/roscpp && mkdir build && cd build`
- `CXX=/usr/bin/clang++ C=/usr/bin/clang cmake -DCMAKE_CXX_FLAGS='-stdlib=libc++' ..`
- `make`

---

Any idea? If you confirm it is likely a `gencpp` issue, I'll fill a bug report there.

**Comment by venabled** [comment]
I'm currently having the same issue. Was there a resolution?

**Comment by kyonifer** [comment]
Second error goes away if you remove the offending forward declaration.

**Comment by dirk-thomas** [comment]
The first described error is a duplicate of ros/roscpp_core#15.

**Comment by dirk-thomas** [comment]
The second error is (as you already mentioned) gencpp specific: https://github.com/ros/gencpp/blob/groovy-devel/src/gencpp/__init__.py#L53. Please fill a ticket there. It might help if you could investigate the problem on your machine and propose a patch since we currently can't reproduce the problem.

**Comment by venabled** [comment]
@dirk-thomas We found the issue was actually in gencpp_traits, not sure where we should file that. We came up with a patch for macports, but not really a .patch file, as @kyonifer just did an inline replacement. Let me know where/how we should proceed

https://github.com/kyonifer/ros-macports/commit/67627ad78ade49ee8aa620f1b722b0e34045db5b

**Comment by kyonifer** [comment]
Removing the allocator forward decl let it build with mav clang/libc++,
without the need for a replacement include. Not sure if this will cause
issues with other compilers.

**Comment by dirk-thomas** [comment]
It looks like that the issue has been fixed in another repo: ros/roscpp_core#15

I will mark this as closed. If there is still a problem please comment with more information and the issue can be reopened.
